#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 blender-web contributors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Refresh the served Python bundle (web/py/gen/) from the REAL sources so the
# M5 replay harness never drifts from the committed files. These copies are the
# staging inputs m5-boot.js fetches over HTTP and writes into WasmFS at /m5.
# gen/ is git-ignored: it is a build artifact, regenerated by running this.
#
# Sources (unchanged authorities):
#   sandbox/m5-prep/sessions/m5_core.py        -> gen/m5_core.py
#   sandbox/corpus-prep/state_dump.py          -> gen/state_dump.py
#   upstream/tests/python/ui_simulate/modules/easy_keys.py     -> gen/easy_keys.py
#   upstream/tests/python/ui_simulate/modules/ui_test_utils.py -> gen/ui_test_utils.py
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
ROOT="$(pwd)"
GEN="$ROOT/sandbox/m5-prep/web/py/gen"
mkdir -p "$GEN"

cp "$ROOT/sandbox/m5-prep/sessions/m5_core.py"                         "$GEN/m5_core.py"
cp "$ROOT/sandbox/corpus-prep/state_dump.py"                           "$GEN/state_dump.py"
cp "$ROOT/upstream/tests/python/ui_simulate/modules/easy_keys.py"      "$GEN/easy_keys.py"
cp "$ROOT/upstream/tests/python/ui_simulate/modules/ui_test_utils.py"  "$GEN/ui_test_utils.py"

echo "staged 4 files into $GEN"
ls -la "$GEN"
